backend: ollama
model: gpt-oss:20b
prompt: narendra_nli_nonbinary
dset_path: data/contract-nli/test.json
dset_type: contract_nli
structure: None
binary: False
options: {
    "temperature": 1.,
    "num_ctx": 4096
}