backend: ollama
model: gemma4:26b
prompt: nli4wills_concise
structure: null
dset_path: data/nli4wills/Idaho/original_datasets/test.csv
dset_type: nli4wills
binary: False
options: {
    "temperature": 0.5,
    "num_ctx": 16384,
    "num_predict": 5000
}
think: True