backend: ollama
model: ministral-3:3b
prompt: narendra_nli_nonbinary_concise
structure: NLIResponse
dset_path: data/contract-nli/test.json
dset_type: contract_nli
binary: False
options: {
    "temperature": 0.4,
    "num_ctx": 16384,
    "num_predict": 5000
}
think: False