# required_config_keys = ["model", "prompt", "binary", "think", "structure", "options"]
model: llama3.1:8b
prompt: narendra_nli
structure: NLIReversed
binary: False
options: {
    "temperature": 0.1,
}